package com.cra.backend.service;

import com.cra.backend.dto.OrganizationRequestDto;
import com.cra.backend.dto.OrganizationResponseDto;
import com.cra.backend.entity.Organization;
import com.cra.backend.repository.OrganizationRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * OrganizationService — The business logic layer.
 *
 * WHAT IS THE SERVICE LAYER?
 * The service sits between the controller and the repository.
 * It contains your BUSINESS LOGIC — the rules of what your application does.
 *
 * RESPONSIBILITIES OF A SERVICE:
 *   1. Validate business rules (e.g., "can't create duplicate organizations")
 *   2. Coordinate between repositories (e.g., a single operation touching multiple tables)
 *   3. Map between DTOs and Entities
 *   4. Handle transactions
 *   5. Apply business transformations before saving or returning data
 *
 * WHY NOT PUT LOGIC IN THE CONTROLLER?
 * Controllers should be thin — they only handle HTTP concerns (parsing request,
 * returning response). Business logic in controllers becomes impossible to reuse,
 * test, or maintain. The service layer keeps concerns separated.
 *
 * @Service → Spring detects this and registers it as a managed bean.
 *            The controller can then @Autowired / inject it.
 *
 * @RequiredArgsConstructor (Lombok) → Generates a constructor for all final fields.
 *   This is the recommended way to do dependency injection in Spring:
 *   Constructor injection > Field injection (@Autowired on field).
 *   Reason: testable, immutable, fails fast at startup if dependencies are missing.
 *
 * @Slf4j (Lombok) → Injects: private static final Logger log = LoggerFactory.getLogger(...);
 *   Use log.info(), log.debug(), log.error() to write logs.
 *
 * @Transactional:
 *   Wraps a method in a database transaction.
 *   If anything throws an exception → the entire transaction ROLLS BACK automatically.
 *   readOnly = true → optimization hint: no write operations, DB can optimize reads.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class OrganizationService {

    // Spring injects this automatically via the constructor generated by @RequiredArgsConstructor
    private final OrganizationRepository organizationRepository;

    /**
     * Creates a new organization.
     *
     * FLOW:
     * 1. Receive validated DTO from controller
     * 2. Map DTO → Entity (convert the "request data" object into a "database object")
     * 3. Save to database via repository
     * 4. Map Entity → ResponseDTO (convert the saved entity back into an "API response" object)
     * 5. Return the response DTO
     *
     * @Transactional ensures that if the save fails halfway, nothing is committed.
     */
    @Transactional
    public OrganizationResponseDto createOrganization(OrganizationRequestDto requestDto) {
        log.info("Creating new organization with name: {}", requestDto.getName());

        // Step 1: Map DTO → Entity using the Builder pattern (generated by @Builder on Organization)
        Organization organization = Organization.builder()
                .name(requestDto.getName())
                .industry(requestDto.getIndustry())
                .status(requestDto.getStatus())
                .build();

        // Step 2: Save to DB. JPA generates: INSERT INTO organizations (name, industry, status, ...) VALUES (...)
        // The returned entity has the auto-generated id and timestamps populated.
        Organization saved = organizationRepository.save(organization);

        log.info("Organization created successfully with id: {}", saved.getId());

        // Step 3: Map Entity → ResponseDTO and return
        return mapToResponseDto(saved);
    }

    /**
     * Retrieves all organizations from the database.
     *
     * readOnly = true → tells Hibernate this transaction won't write anything.
     *                   Hibernate skips "dirty checking" (comparing entity state to DB state),
     *                   making read operations faster.
     */
    @Transactional(readOnly = true)
    public List<OrganizationResponseDto> getAllOrganizations() {
        log.info("Fetching all organizations");

        // findAll() generates: SELECT * FROM organizations
        List<Organization> organizations = organizationRepository.findAll();

        // Convert each entity to a response DTO using Java Streams
        return organizations.stream()
                .map(this::mapToResponseDto)
                .toList();   // Java 16+ shorthand for .collect(Collectors.toList())
    }

    /**
     * Private helper to map an Organization entity to its response DTO.
     *
     * WHY A PRIVATE HELPER?
     * Both createOrganization() and getAllOrganizations() need to do this mapping.
     * Extracting it avoids duplication (DRY principle — Don't Repeat Yourself).
     * Later we'll likely replace this with a dedicated mapper library.
     */
    private OrganizationResponseDto mapToResponseDto(Organization org) {
        return OrganizationResponseDto.builder()
                .id(org.getId())
                .name(org.getName())
                .industry(org.getIndustry())
                .status(org.getStatus())
                .createdAt(org.getCreatedAt())
                .updatedAt(org.getUpdatedAt())
                .build();
    }
}
